# install these with `brew bundle ~/Brewfile`.
install ack
install archey
install aspell
install autoconf
install automake
install ccze
install cscope
install ctags
install gdbm
install git
install htop-osx
install hub
install leiningen
install libevent
install libtool
install lua
install luajit
install mongodb
install node
install openssl
install pcre
install pkg-config
install python3
install readline
install reattach-to-user-namespace
install scons
install selenium-server-standalone
install sqlite
install the_silver_searcher
install tig
install tmux
install trash
install tree
install xz
install zsh
