windows:
  - name: helix
    root: ~/code/js/helix-ui
    layout: even-horizontal
    panes:
      - nvm use 8
      - nvm use 8
  - name: svr
    root: ~/code/js/snappit-visual-regression
    layout: even-horizontal
    panes:
      - nvm use 8
      - nvm use 8
  - name: tesla
    root: ~/code/tesla
  - name: gd
    root: ~/code/js/global-dashboard
    layout: even-horizontal
    panes:
      - nvm use 8
      - nvm use 8
  - name: top
    root: ~/
    panes:
      - sudo htop
