windows:
  - name: helix
    root: ~/code/js/helix-ui
    layout: even-horizontal
    panes:
      - nvm use 7
      - nvm use 7
  - name: svr
    root: ~/code/js/snappit-visual-regression
    layout: even-horizontal
    panes:
      - nvm use 8
      - nvm use 8
  - name: misc
    root: ~/notes/
  - name: top
    root: ~/
    panes:
      - sudo htop
